//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor desencriptado:  .
        /// </summary>
        internal static string DecrypVal {
            get {
                return ResourceManager.GetString("DecrypVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ingresó texto para validar :(.
        /// </summary>
        internal static string EmptyInput {
            get {
                return ResourceManager.GetString("EmptyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor encriptado: .
        /// </summary>
        internal static string Encrypdated {
            get {
                return ResourceManager.GetString("Encrypdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar Datos.
        /// </summary>
        internal static string lblClean {
            get {
                return ResourceManager.GetString("lblClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa el texto a validar.
        /// </summary>
        internal static string lblInputText {
            get {
                return ResourceManager.GetString("lblInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blanca Cid - SSA México.
        /// </summary>
        internal static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo Entregable - &quot;Seguridad en Aplicaciones y Mejores Prácticas de Seguridad en Codificación&quot;.
        /// </summary>
        internal static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validar.
        /// </summary>
        internal static string lblValidate {
            get {
                return ResourceManager.GetString("lblValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor enmascarado:  .
        /// </summary>
        internal static string MaskedValue {
            get {
                return ResourceManager.GetString("MaskedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada Sanitizada: .
        /// </summary>
        internal static string Sanitized {
            get {
                return ResourceManager.GetString("Sanitized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sha-256 Hash: .
        /// </summary>
        internal static string SHAVal {
            get {
                return ResourceManager.GetString("SHAVal", resourceCulture);
            }
        }
    }
}
